### ISSUE TITLE
Como rodar a plataforma?

### ISSUE THREAD

**Issue by hsecreto** [KonkerLabs/konker-platform#412]
Baixei o projeto do github a apareceram vários erros de java e javascript, porém o projeto compilou. A partir daí, segui os passos da documentação disponibilizada no github para rodar as aplicações em docker, mas não funcionou. Não está muito claro de como especificar as portas de forma correta e qual a relação entre os serviços. Gostaria de modificar o projeto e ter o ambiente de desenvolvimento pronto. Há alguma documentação mais especifica que eu possa seguir?

**Comment by sonecabr** [comment]
Ola @hsecreto , obrigado pelo report. Existe mais de uma opçao, a mais simples delas é rodar a plataforma com o container consolidado...https://hub.docker.com/r/konkerlabs/konker-platform. Para o caso de voce extender a plataforma, ai realmente precisa ir um pouco mais fundo em cada modulo. Nossa documentação atual cobre casos de uso da plataforma (https://konker.atlassian.net/wiki/spaces/DEV/pages/28180518/Guia+de+Uso+da+Plataforma+Konker), mas realmente ainda precisamos trabalhar um pouco mais para cobrir o suporte a desenvolvedores de forma adequada. Vou adicionar estes detalhes na nossa documentaçao assim que possivel, mas gostaria de oferecer uma alternativa, podemos encontrar uma agenda para conversar de dev para dev a respeito dos modulos da plataforma, isso pode te ajudar a construir o ambiente, o que acha?
